-- Tabla de membresia
create table Membresia (
ID_membresia number generated by default on null as identity,
Membresia_Tipo_membresia varchar2(10),
Membresia_Inicio_membresia TIMESTAMP,
Membresia_Fin_membreia TIMESTAMP,
Membresia_precio number,
Membresia_Estado_membresia number,
constraint PK_Membresia primary key(ID_membresia)
);


--Tabla de clientes
Create table Cliente (
ID_cliente number generated by default on null as identity,
Cliente_Username varchar2(15) not null,
Cliente_Password varchar2(100) not null,
Cliente_Nombre varchar2(25) not null,
Cliente_Apellido varchar2(25) not null,
Cliente_Fecha_nacimiento timestamp,
Cliente_Fecha_registro timestamp,
Cliente_Correo_electronico varchar2(50),
Cliente_Foto_perfil varchar2(200),
Cliente_rol number,
FK_ID_membresia number,
constraint PK_Cliente primary key (ID_cliente),
constraint FK_cliente_membresia Foreign key (FK_ID_membresia) references Membresia(ID_membresia)
);


--Tabla de temporada 
create table Temporada(
ID_temporada number generated by default on null as identity,
Temporada_Nombre_temporada varchar2(25),
Temporada_Ganancia number(*,2) not null,
Temporada_Inicio_temporada timestamp,
Temporada_Fin_temporada timestamp,
constraint PK_temporada primary key(ID_temporada)
);


--tabla de recompensa 
create table Recompensa(
ID_recompensa number generated by default on null as identity,
Recompensa_Cantidad_recompensa number(*,2),
FK_ID_Temporada number not null,
FK_ID_Cliente number not null,
constraint PK_recompensa primary key(ID_recompensa),
constraint FK_recompensa_Temporada foreign key(FK_ID_Temporada) references Temporada(ID_temporada),
constraint FK_recompensa_Cliente foreign key(FK_ID_Cliente) references Cliente(ID_cliente)
);

--tabla de jornada
create table Jornada(
ID_jornada number generated by default on null as identity,
Jornada_Fase number not null,
Jornada_Fecha_inicio timestamp,
Jornada_Fechar_fin timestamp,
FK_ID_temporada number,
constraint PK_jornada primary key(ID_jornada),
constraint FK_jornada_temporada foreign key(FK_ID_temporada) references Temporada(ID_temporada)
);

--tabla de evento
create table Evento(
ID_evento number generated by default on null as identity,
Evento_Puntaje_local number not null,
Evento_Puntaje_visitante number not null,
FK_ID_jornada number not null,
FK_ID_equipo_local number not null,
FK_ID_equipo_visitante number not null,
FK_ID_deporte number not null,
CONSTRAINT PK_evento primary key (ID_evento),
constraint FK_evento_jornada foreign key (FK_ID_jornada) references Jornada(ID_jornada),
constraint FK_evento_equipo_local foreign key (FK_ID_equipo_local) references Equipo(ID_equipo),
constraint FK_evento_equipo_visitante foreign key (FK_ID_equipo_visitante) references Equipo(ID_equipo),
constraint FK_evento_deporte foreign key (FK_ID_deporte) references Deporte(ID_deporte)
);


--tabla Estado evento deportivo
Create table Estado_EventoDeportivo(
ID_estado_evento number generated by default on null as identity,
Estado_evento_color varchar2(25) not null, 
constraint PK_ID_estado_evento primary key (ID_estado_evento)
);


--tabla de equipo
Create table Equipo(
ID_equipo number generated by default on null as identity,
Equipo_nombre varchar2(50) not null,
constraint PK_equipo primary key(ID_equipo)
);


--tabla de deporte
create table deporte(
ID_deporte number generated by default on null as identity,
Deporte_Nombre number not null,
Deporte_img varchar2(200) not null, 
Deporte_color varchar2(25) not null,
constraint PK_deporte primary key (ID_deporte)
);



--tabla de prediccion
create table Prediccion(
ID_prediccion number generated by default on null as identity,
Prediccion_local number not null,
Prediccion_visitante number not null,
Prediccion_puntaje number not null,
FK_ID_cliente number not null,
FK_ID_evento number not null,
constraint PK_prediccion primary key(ID_prediccion),
constraint FK_prediccion_cliente foreign key(FK_ID_cliente) references Cliente(ID_cliente),
constraint FK_prediccion_evento foreign key(FK_ID_evento) references Evento(ID_evento)
);

drop table Prediccion;


--tabla de mensaje
create table Mensaje(
ID_mensaje number generated by default on null as identity,
Mensaje_contenido varchar2(2000),
FK_ID_chat int not null,
constraint PK_ID_mensaje primary key (ID_mensaje),
constraint FK_ID_chat foreign key (FK_ID_chat) references Chat(ID_chat)
);


drop table Mensaje;


--tabla de chat
Create table Chat(
ID_chat number generated by default on null as identity,
FK_ID_cliente number not null,
FK_ID_administrador number not null, 
constraint PK_chat primary key (ID_chat),
constraint FK_chat_cliente foreign key(FK_ID_cliente) references Cliente(ID_cliente),
constraint FK_chat_administrador foreign key(FK_ID_administrador) references Cliente(ID_cliente)
);



create table Usuario_Membresia(
ID_usuario_membresia number generated by default on null as identity,
FK_ID_cliente number not null,
FK_ID_membresia number not null,
FK_ID_temporada number not null,
constraint PK_ID_usuario primary key (ID_usuario_membresia),
constraint FK_ID_membresia foreign key (FK_ID_membresia) references Membresia(ID_membresia),
constraint FK_ID_cliente foreign key (FK_ID_cliente) references Cliente(ID_cliente),
constraint FK_ID_temporada foreign key (FK_ID_temporada) references Temporada(ID_temporada)
);




--Tabla de ranking
Create table Ranking(
ID_ranking number generated by default on null as identity,
Ranking_Incremento number(*,2),
FK_ID_Temporada number not null,
FK_ID_Cliente number not null, 
FK_ID_Usuario_membresia number not null,
Ranking_P10 number,
Ranking_P5 number,
Ranking_P3 number,
Ranking_P0 number,
Ranking_total number,
CONSTRAINT PK_ranking primary key(ID_ranking),
CONSTRAINT FK_ranking_temporada foreign key(FK_ID_Temporada) references Temporada(ID_temporada),
CONSTRAINT FK_ranking_usuario_membresia foreign key(FK_ID_Usuario_membresia) references Usuario_Membresia(ID_usuario_membresia),
constraint FK_ranking_cliente foreign key(FK_ID_Cliente) references Cliente(ID_cliente)
);
